/* OpportunityScout dashboard — renders window.SCOUT_DATA (generated by scout/scraper.py). */
(function () {
  "use strict";

  var DATA = window.SCOUT_DATA || { categories: [], opportunities: [], status: {}, scrapeState: {} };
  var STATE = DATA.scrapeState || {};
  var APPLIED = {};
  var HIDDEN = {};
  ((DATA.status || {}).applied || []).forEach(function (id) { APPLIED[id] = true; });
  ((DATA.status || {}).notInterested || []).forEach(function (id) { HIDDEN[id] = true; });
  var REPO = DATA.repo || "hughgingell2-collab/second-order-demos";
  var TODAY = new Date();
  TODAY.setHours(0, 0, 0, 0);
  var CHANGED_WINDOW_DAYS = 21;

  /* ---------- theme ---------- */
  var root = document.documentElement;
  var theme = null;
  try { theme = localStorage.getItem("so-theme"); } catch (e) {}
  if (!theme) theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  applyTheme(theme);
  document.getElementById("themeToggle").addEventListener("click", function () {
    theme = theme === "dark" ? "light" : "dark";
    applyTheme(theme);
    try { localStorage.setItem("so-theme", theme); } catch (e) {}
  });
  function applyTheme(t) {
    if (t === "dark") root.setAttribute("data-theme", "dark");
    else root.removeAttribute("data-theme");
  }

  /* ---------- helpers ---------- */
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function daysUntil(iso) {
    if (!iso) return null;
    var d = new Date(iso + "T00:00:00");
    if (isNaN(d)) return null;
    return Math.round((d - TODAY) / 86400000);
  }
  function fmtDate(iso) {
    if (!iso) return "—";
    var d = new Date(iso + "T00:00:00");
    if (isNaN(d)) return iso;
    return d.toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" });
  }
  function deadlineBadge(item) {
    var days = daysUntil(item.deadline);
    if (days === null) return { cls: "rolling", label: item.cadence ? "Rolling / recurring" : "See page" };
    if (days < 0) return { cls: "closed", label: "Closed — next cycle" };
    if (days <= 30) return { cls: "due-soon", label: days + "d left" };
    if (days <= 90) return { cls: "due-mid", label: days + "d left" };
    return { cls: "due-far", label: days + "d left" };
  }
  function recentlyChanged(id) {
    var st = STATE[id];
    if (!st || !st.changedAt) return false;
    var d = new Date(st.changedAt);
    return !isNaN(d) && (TODAY - d) / 86400000 <= CHANGED_WINDOW_DAYS;
  }
  function statusBadges(item) {
    var html = "";
    if (APPLIED[item.id]) html += '<span class="badge applied">applied ✓</span> ';
    if (HIDDEN[item.id]) html += '<span class="badge closed">hidden</span> ';
    var b = deadlineBadge(item);
    html += '<span class="badge ' + b.cls + '">' + esc(b.label) + "</span>";
    if (recentlyChanged(item.id)) html += ' <span class="badge changed">page changed</span>';
    var st = STATE[item.id];
    if (st && st.error) html += ' <span class="badge error" title="' + esc(st.error) + '">fetch error</span>';
    return html;
  }
  function sortValDeadline(item) {
    var days = daysUntil(item.deadline);
    if (days === null) return 99998;
    if (days < 0) return 99999;
    return days;
  }
  function feedbackLink(id, action) {
    var label = action === "applied" ? "I applied to this" : "Not interested / hide this";
    var params = new URLSearchParams({
      title: "scout: " + action + " " + id,
      body: label + ": `" + id + "`.\n\nJust press **Submit new issue** — the feedback bot will record it, update the dashboard, and close this issue automatically.",
      labels: "scout-feedback"
    });
    return "https://github.com/" + REPO + "/issues/new?" + params.toString();
  }

  /* ---------- tabs (one per category + about) ---------- */
  var CATS = DATA.categories.map(function (c) { return c.key; });
  var TABS = CATS.concat(["about"]);
  var tabsNav = document.querySelector("nav.tabs");
  DATA.categories.forEach(function (c) {
    var btn = document.createElement("button");
    btn.dataset.tab = c.key;
    btn.setAttribute("aria-selected", "false");
    btn.textContent = c.tab || c.label;
    tabsNav.insertBefore(btn, tabsNav.querySelector('button[data-tab="about"]'));
  });
  var tabButtons = Array.prototype.slice.call(tabsNav.querySelectorAll("button"));
  function showTab(id, push) {
    if (TABS.indexOf(id) === -1) id = TABS[0];
    tabButtons.forEach(function (btn) {
      btn.setAttribute("aria-selected", btn.dataset.tab === id ? "true" : "false");
    });
    TABS.forEach(function (t) {
      var panel = document.getElementById("panel-" + t);
      if (panel) panel.hidden = t !== id;
    });
    if (push !== false) {
      try { history.replaceState(null, "", "#" + id); } catch (e) { location.hash = id; }
    }
  }
  tabsNav.addEventListener("click", function (ev) {
    var btn = ev.target.closest("button");
    if (btn) showTab(btn.dataset.tab);
  });
  window.addEventListener("hashchange", function () {
    showTab((location.hash || "#" + TABS[0]).slice(1), false);
  });

  /* ---------- category panels ---------- */
  var main = document.querySelector("main");
  var aboutPanel = document.getElementById("panel-about");
  var genDate = DATA.generated ? DATA.generated.slice(0, 10) : null;
  var freshText = genDate
    ? "Catalog last regenerated " + genDate + " · scraper runs weekly (Tuesday morning AEST) and opens a GitHub issue — with I-applied / not-interested buttons — when a watched page changes."
    : "Scraper has not run yet.";

  DATA.categories.forEach(function (cat) {
    var rows = DATA.opportunities.filter(function (o) { return o.category === cat.key; });
    var section = document.createElement("section");
    section.id = "panel-" + cat.key;
    section.setAttribute("role", "tabpanel");
    section.setAttribute("aria-label", cat.label);
    section.hidden = true;
    section.innerHTML =
      '<div class="section-intro"><h1>' + esc(cat.label) + "</h1>" +
      "<p>" + esc(cat.intro || "") + "</p>" +
      '<p class="freshness">' + esc(freshText) + "</p></div>" +
      '<div class="controls">' +
      '<input type="search" placeholder="Search…" aria-label="Search ' + esc(cat.label) + '">' +
      '<label class="hide-toggle"><input type="checkbox" class="show-hidden"> show hidden</label>' +
      '<button class="reset-link" hidden>Reset</button>' +
      '<span class="count"></span></div>' +
      '<div class="table-wrap"><table><thead><tr>' +
      '<th scope="col"><button data-key="name">Opportunity<span class="arrow"></span></button></th>' +
      '<th scope="col"><button data-key="prepare">Prepare<span class="arrow"></span></button></th>' +
      '<th scope="col" class="num"><button data-key="deadline">Deadline<span class="arrow"></span></button></th>' +
      "</tr></thead><tbody></tbody></table></div>" +
      '<div class="empty" hidden>No results — <button>reset</button></div>';
    main.insertBefore(section, aboutPanel);
    wireSection(section, rows);
  });

  function wireSection(panel, rows) {
    var tbody = panel.querySelector("tbody");
    var tableWrap = panel.querySelector(".table-wrap");
    var emptyBox = panel.querySelector(".empty");
    var countEl = panel.querySelector(".count");
    var headers = Array.prototype.slice.call(panel.querySelectorAll("thead th button"));
    var searchEl = panel.querySelector('input[type="search"]');
    var showHiddenEl = panel.querySelector(".show-hidden");
    var resetBtn = panel.querySelector(".reset-link");
    var sort = { key: "deadline", dir: 1 };
    var sortVals = {
      name: function (r) { return r.name.toLowerCase(); },
      prepare: function (r) { return (r.prepare || "").toLowerCase(); },
      deadline: sortValDeadline
    };

    function render() {
      var q = (searchEl.value || "").trim().toLowerCase();
      var shown = rows.filter(function (r) {
        if (HIDDEN[r.id] && !showHiddenEl.checked) return false;
        if (q && [r.name, r.blurb, r.prepare, r.sub].join(" ").toLowerCase().indexOf(q) === -1) return false;
        return true;
      });
      var sv = sortVals[sort.key] || sortVals.deadline;
      shown = shown.slice().sort(function (a, b) {
        var va = sv(a), vb = sv(b);
        return va < vb ? -sort.dir : va > vb ? sort.dir : 0;
      });
      headers.forEach(function (h) {
        var th = h.parentElement, arrow = h.querySelector(".arrow");
        if (h.dataset.key === sort.key) {
          th.setAttribute("aria-sort", sort.dir === 1 ? "ascending" : "descending");
          arrow.textContent = sort.dir === 1 ? "▲" : "▼";
        } else { th.removeAttribute("aria-sort"); arrow.textContent = ""; }
      });
      tbody.innerHTML = shown.map(function (r) {
        return '<tr data-id="' + esc(r.id) + '"' + (HIDDEN[r.id] ? ' class="dimmed"' : "") + ">" +
          '<td><div class="cell-main">' + esc(r.name) +
          (r.sub ? ' <span class="badge cat">' + esc(r.sub) + "</span>" : "") +
          '</div><div class="cell-sub">' + esc(r.blurb || "") + "</div></td>" +
          '<td class="prep">' + esc(r.prepare || "—") + "</td>" +
          '<td class="num"><div>' + esc(r.deadline ? fmtDate(r.deadline) : (r.cadence || "—")) +
          "</div><div>" + statusBadges(r) + "</div></td></tr>";
      }).join("");
      Array.prototype.slice.call(tbody.querySelectorAll("tr")).forEach(function (tr) {
        tr.tabIndex = 0;
        function open() {
          var item = rows.filter(function (r) { return r.id === tr.dataset.id; })[0];
          if (item) openDetail(item);
        }
        tr.addEventListener("click", open);
        tr.addEventListener("keydown", function (ev) {
          if (ev.key === "Enter" || ev.key === " ") { ev.preventDefault(); open(); }
        });
      });
      resetBtn.hidden = !q && !showHiddenEl.checked;
      tableWrap.hidden = shown.length === 0;
      emptyBox.hidden = shown.length !== 0;
      countEl.textContent = shown.length + " of " + rows.length + " shown";
    }
    headers.forEach(function (h) {
      h.addEventListener("click", function () {
        if (sort.key === h.dataset.key) sort.dir = -sort.dir;
        else { sort.key = h.dataset.key; sort.dir = 1; }
        render();
      });
    });
    searchEl.addEventListener("input", render);
    showHiddenEl.addEventListener("change", render);
    function reset() { searchEl.value = ""; showHiddenEl.checked = false; render(); }
    resetBtn.addEventListener("click", reset);
    emptyBox.querySelector("button").addEventListener("click", reset);
    render();
  }

  /* ---------- detail slide-over ---------- */
  var overlay = document.getElementById("overlay");
  var slideover = document.getElementById("slideover");
  var lastFocus = null;
  function openDetail(item) {
    lastFocus = document.activeElement;
    var st = STATE[item.id] || {};
    var html = '<button class="close" aria-label="Close details">×</button>';
    html += "<h2>" + esc(item.name) + "</h2>";
    if (item.sub) html += '<p class="sub">' + esc(item.sub) + "</p>";
    html += "<p>" + statusBadges(item) + "</p>";
    if (item.blurb) html += '<p class="detail-blurb">' + esc(item.blurb) + "</p>";
    if (item.prepare) html += '<p class="detail-blurb"><strong>Prepare:</strong> ' + esc(item.prepare) + "</p>";
    html += "<dl>";
    [["Deadline", item.deadline ? fmtDate(item.deadline) : null],
     ["Cadence", item.cadence],
     ["Notes", item.deadlineNote]].forEach(function (p) {
      if (p[1]) html += "<dt>" + esc(p[0]) + "</dt><dd>" + esc(p[1]) + "</dd>";
    });
    html += "</dl>";
    if (item.url) {
      html += '<a class="apply-btn" href="' + esc(item.url) + '" target="_blank" rel="noopener">Open official page ↗</a>';
    }
    html += '<div class="feedback-row">' +
      '<a href="' + esc(feedbackLink(item.id, "applied")) + '" target="_blank" rel="noopener">✅ I applied</a>' +
      '<a href="' + esc(feedbackLink(item.id, "hide")) + '" target="_blank" rel="noopener">🚫 Not interested</a></div>';
    html += '<div class="scrape-box">';
    if (st.lastChecked) {
      html += "<strong>Scraper status</strong><br>Last checked: " + esc(st.lastChecked.slice(0, 10));
      if (st.dates && st.dates.length) html += "<br>Dates spotted on page: " + st.dates.map(fmtDate).map(esc).join(", ");
      if (st.changedAt) html += "<br>Last change detected: " + esc(st.changedAt.slice(0, 10));
      if (st.error) html += "<br>Last fetch error: " + esc(st.error);
    } else {
      html += "<strong>Scraper status</strong><br>Not yet scanned — runs weekly via GitHub Actions.";
    }
    html += "</div>";
    slideover.innerHTML = html;
    overlay.classList.add("open");
    slideover.classList.add("open");
    var closeBtn = slideover.querySelector(".close");
    closeBtn.addEventListener("click", closeDetail);
    closeBtn.focus();
    slideover.addEventListener("keydown", trapFocus);
  }
  function closeDetail() {
    overlay.classList.remove("open");
    slideover.classList.remove("open");
    slideover.removeEventListener("keydown", trapFocus);
    if (lastFocus && lastFocus.focus) lastFocus.focus();
  }
  overlay.addEventListener("click", closeDetail);
  document.addEventListener("keydown", function (ev) {
    if (ev.key === "Escape" && slideover.classList.contains("open")) closeDetail();
  });
  function trapFocus(ev) {
    if (ev.key !== "Tab") return;
    var focusables = slideover.querySelectorAll("button, a[href]");
    if (!focusables.length) return;
    var first = focusables[0], last = focusables[focusables.length - 1];
    if (ev.shiftKey && document.activeElement === first) { ev.preventDefault(); last.focus(); }
    else if (!ev.shiftKey && document.activeElement === last) { ev.preventDefault(); first.focus(); }
  }

  showTab((location.hash || "#" + TABS[0]).slice(1), false);
})();
