/* OpportunityScout dashboard — renders window.SCOUT_DATA (generated by scout/scraper.py). */
(function () {
  "use strict";

  var DATA = window.SCOUT_DATA || { programs: [], scholarships: [], startupSupport: [], scrapeState: {} };
  var STATE = DATA.scrapeState || {};
  var TODAY = new Date();
  TODAY.setHours(0, 0, 0, 0);
  var CHANGED_WINDOW_DAYS = 21;

  /* ---------- theme ---------- */
  var root = document.documentElement;
  var theme = null;
  try { theme = localStorage.getItem("so-theme"); } catch (e) {}
  if (!theme) theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  applyTheme(theme);
  document.getElementById("themeToggle").addEventListener("click", function () {
    theme = theme === "dark" ? "light" : "dark";
    applyTheme(theme);
    try { localStorage.setItem("so-theme", theme); } catch (e) {}
  });
  function applyTheme(t) {
    if (t === "dark") root.setAttribute("data-theme", "dark");
    else root.removeAttribute("data-theme");
  }

  /* ---------- tabs ---------- */
  var TABS = ["study", "scholarships", "startups", "about"];
  var tabButtons = Array.prototype.slice.call(document.querySelectorAll("nav.tabs button"));
  function showTab(id, push) {
    if (TABS.indexOf(id) === -1) id = TABS[0];
    tabButtons.forEach(function (btn) {
      var active = btn.dataset.tab === id;
      btn.setAttribute("aria-selected", active ? "true" : "false");
    });
    TABS.forEach(function (t) {
      document.getElementById("panel-" + t).hidden = t !== id;
    });
    if (push !== false) {
      try { history.replaceState(null, "", "#" + id); } catch (e) { location.hash = id; }
    }
  }
  tabButtons.forEach(function (btn) {
    btn.addEventListener("click", function () { showTab(btn.dataset.tab); });
  });
  window.addEventListener("hashchange", function () {
    showTab((location.hash || "#study").slice(1), false);
  });
  showTab((location.hash || "#study").slice(1), false);

  /* ---------- helpers ---------- */
  function daysUntil(iso) {
    if (!iso) return null;
    var d = new Date(iso + "T00:00:00");
    if (isNaN(d)) return null;
    return Math.round((d - TODAY) / 86400000);
  }
  function fmtDate(iso) {
    if (!iso) return "—";
    var d = new Date(iso + "T00:00:00");
    if (isNaN(d)) return iso;
    return d.toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" });
  }
  function deadlineBadge(item) {
    var days = daysUntil(item.deadline);
    if (days === null) return { cls: "rolling", label: item.cadence ? "Rolling / batch" : "See page" };
    if (days < 0) return { cls: "closed", label: "Closed — next cycle" };
    if (days <= 30) return { cls: "due-soon", label: days + "d left" };
    if (days <= 90) return { cls: "due-mid", label: days + "d left" };
    return { cls: "due-far", label: days + "d left" };
  }
  function recentlyChanged(id) {
    var st = STATE[id];
    if (!st || !st.changedAt) return false;
    var d = new Date(st.changedAt);
    if (isNaN(d)) return false;
    return (TODAY - d) / 86400000 <= CHANGED_WINDOW_DAYS;
  }
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function badgeHtml(item) {
    var b = deadlineBadge(item);
    var html = '<span class="badge ' + b.cls + '">' + esc(b.label) + "</span>";
    if (recentlyChanged(item.id)) html += ' <span class="badge changed">page changed</span>';
    var st = STATE[item.id];
    if (st && st.error) html += ' <span class="badge error" title="' + esc(st.error) + '">fetch error</span>';
    return html;
  }
  function sortValDeadline(item) {
    var days = daysUntil(item.deadline);
    if (days === null) return 99998;      // rolling — after dated, before closed
    if (days < 0) return 99999;           // closed last
    return days;
  }

  /* ---------- generic table section ---------- */
  function makeSection(cfg) {
    var panel = document.getElementById("panel-" + cfg.tab);
    var controls = panel.querySelector(".controls");
    var tbody = panel.querySelector("tbody");
    var tableWrap = panel.querySelector(".table-wrap");
    var emptyBox = panel.querySelector(".empty");
    var countEl = panel.querySelector(".count");
    var headers = Array.prototype.slice.call(panel.querySelectorAll("thead th button"));
    var searchEl = panel.querySelector('input[type="search"]');
    var selects = Array.prototype.slice.call(controls.querySelectorAll("select"));
    var resetBtn = panel.querySelector(".reset-link");
    var sort = { key: cfg.defaultSort, dir: 1 };

    // Populate filter dropdowns from the data itself so catalog edits need no HTML change.
    selects.forEach(function (sel) {
      var key = sel.dataset.filter;
      var labels = cfg.optionLabels && cfg.optionLabels[key];
      var seen = [];
      cfg.rows.forEach(function (r) {
        var v = r[key];
        if (v != null && seen.indexOf(v) === -1) seen.push(v);
      });
      seen.sort();
      seen.forEach(function (v) {
        var opt = document.createElement("option");
        opt.value = v;
        opt.textContent = (labels && labels[v]) || v;
        sel.appendChild(opt);
      });
    });

    function activeRows() {
      var q = (searchEl && searchEl.value || "").trim().toLowerCase();
      return cfg.rows.filter(function (r) {
        for (var i = 0; i < selects.length; i++) {
          var sel = selects[i], v = sel.value;
          if (v !== "all" && String(cfg.filterVal(r, sel.dataset.filter)) !== v) return false;
        }
        if (q && cfg.searchText(r).toLowerCase().indexOf(q) === -1) return false;
        return true;
      });
    }
    function render() {
      var rows = activeRows();
      var col = cfg.columns.filter(function (c) { return c.key === sort.key; })[0] || cfg.columns[0];
      rows = rows.slice().sort(function (a, b) {
        var va = col.sortVal(a), vb = col.sortVal(b);
        if (va < vb) return -1 * sort.dir;
        if (va > vb) return 1 * sort.dir;
        return 0;
      });
      headers.forEach(function (h) {
        var th = h.parentElement;
        var arrow = h.querySelector(".arrow");
        if (h.dataset.key === sort.key) {
          th.setAttribute("aria-sort", sort.dir === 1 ? "ascending" : "descending");
          arrow.textContent = sort.dir === 1 ? "▲" : "▼";
        } else {
          th.removeAttribute("aria-sort");
          arrow.textContent = "";
        }
      });
      tbody.innerHTML = rows.map(cfg.rowHtml).join("");
      Array.prototype.slice.call(tbody.querySelectorAll("tr")).forEach(function (tr) {
        tr.tabIndex = 0;
        function open() {
          var item = cfg.rows.filter(function (r) { return r.id === tr.dataset.id; })[0];
          if (item) openDetail(item, cfg);
        }
        tr.addEventListener("click", open);
        tr.addEventListener("keydown", function (ev) {
          if (ev.key === "Enter" || ev.key === " ") { ev.preventDefault(); open(); }
        });
      });
      var anyFilter = selects.some(function (s) { return s.value !== "all"; }) || (searchEl && searchEl.value);
      resetBtn.hidden = !anyFilter;
      tableWrap.hidden = rows.length === 0;
      emptyBox.hidden = rows.length !== 0;
      countEl.textContent = rows.length + " of " + cfg.rows.length + " shown";
    }
    headers.forEach(function (h) {
      h.addEventListener("click", function () {
        if (sort.key === h.dataset.key) sort.dir = -sort.dir;
        else { sort.key = h.dataset.key; sort.dir = 1; }
        render();
      });
    });
    selects.forEach(function (s) { s.addEventListener("change", render); });
    if (searchEl) searchEl.addEventListener("input", render);
    function reset() {
      selects.forEach(function (s) { s.value = "all"; });
      if (searchEl) searchEl.value = "";
      render();
    }
    resetBtn.addEventListener("click", reset);
    emptyBox.querySelector("button").addEventListener("click", reset);
    render();
  }

  /* ---------- detail slide-over ---------- */
  var overlay = document.getElementById("overlay");
  var slideover = document.getElementById("slideover");
  var lastFocus = null;
  function openDetail(item, cfg) {
    lastFocus = document.activeElement;
    var st = STATE[item.id] || {};
    var pairs = cfg.detailPairs(item);
    var html = '<button class="close" aria-label="Close details">×</button>';
    html += "<h2>" + esc(cfg.detailTitle(item)) + "</h2>";
    html += '<p class="sub">' + esc(cfg.detailSub(item)) + "</p>";
    html += "<p>" + badgeHtml(item) + "</p>";
    html += "<dl>";
    pairs.forEach(function (p) {
      if (p[1]) html += "<dt>" + esc(p[0]) + "</dt><dd>" + esc(p[1]) + "</dd>";
    });
    html += "</dl>";
    if (item.url) {
      html += '<a class="apply-btn" href="' + esc(item.url) + '" target="_blank" rel="noopener">Open official page ↗</a>';
    }
    html += '<div class="scrape-box">';
    if (st.lastChecked) {
      html += "<strong>Scraper status</strong><br>Last checked: " + esc(st.lastChecked.slice(0, 10));
      if (st.dates && st.dates.length) {
        html += "<br>Dates spotted on page: " + st.dates.map(fmtDate).map(esc).join(", ");
      }
      if (st.changedAt) html += "<br>Last change detected: " + esc(st.changedAt.slice(0, 10));
      if (st.error) html += "<br>Last fetch error: " + esc(st.error);
    } else {
      html += "<strong>Scraper status</strong><br>Not yet scanned — runs weekly via GitHub Actions.";
    }
    html += "</div>";
    slideover.innerHTML = html;
    overlay.classList.add("open");
    slideover.classList.add("open");
    var closeBtn = slideover.querySelector(".close");
    closeBtn.addEventListener("click", closeDetail);
    closeBtn.focus();
    slideover.addEventListener("keydown", trapFocus);
  }
  function closeDetail() {
    overlay.classList.remove("open");
    slideover.classList.remove("open");
    slideover.removeEventListener("keydown", trapFocus);
    if (lastFocus && lastFocus.focus) lastFocus.focus();
  }
  overlay.addEventListener("click", closeDetail);
  document.addEventListener("keydown", function (ev) {
    if (ev.key === "Escape" && slideover.classList.contains("open")) closeDetail();
  });
  function trapFocus(ev) {
    if (ev.key !== "Tab") return;
    var focusables = slideover.querySelectorAll("button, a[href]");
    if (!focusables.length) return;
    var first = focusables[0], last = focusables[focusables.length - 1];
    if (ev.shiftKey && document.activeElement === first) { ev.preventDefault(); last.focus(); }
    else if (!ev.shiftKey && document.activeElement === last) { ev.preventDefault(); first.focus(); }
  }

  /* ---------- freshness lines ---------- */
  var genDate = DATA.generated ? DATA.generated.slice(0, 10) : null;
  Array.prototype.slice.call(document.querySelectorAll(".freshness")).forEach(function (el) {
    el.textContent = genDate
      ? "Catalog last regenerated " + genDate + " · scraper runs weekly (Tuesday morning AEST) and opens a GitHub issue when a watched page changes."
      : "Scraper has not run yet.";
  });

  /* ---------- Section: Study ---------- */
  var CAT_LABEL = { "ai-masters": "AI / CS masters", "law-tech": "Law + technology", "mba": "MBA" };
  makeSection({
    tab: "study",
    rows: DATA.programs,
    defaultSort: "deadline",
    optionLabels: { category: CAT_LABEL },
    filterVal: function (r, key) { return r[key]; },
    searchText: function (r) { return [r.university, r.program, r.degree, r.fit].join(" "); },
    columns: [
      { key: "program", sortVal: function (r) { return (r.university + r.program).toLowerCase(); } },
      { key: "category", sortVal: function (r) { return r.category; } },
      { key: "deadline", sortVal: sortValDeadline },
      { key: "tuition", sortVal: function (r) { return r.tuitionSort || 0; } }
    ],
    rowHtml: function (r) {
      return '<tr data-id="' + esc(r.id) + '">' +
        '<td><div class="cell-main">' + esc(r.program) + '</div><div class="cell-sub">' + esc(r.university) + " · " + esc(r.degree) + "</div></td>" +
        '<td><span class="badge cat">' + esc(CAT_LABEL[r.category] || r.category) + "</span></td>" +
        '<td class="num"><div>' + esc(fmtDate(r.deadline)) + "</div><div>" + badgeHtml(r) + "</div></td>" +
        '<td class="num">' + esc(r.tuition || "—") + "</td>" +
        "</tr>";
    },
    detailTitle: function (r) { return r.program; },
    detailSub: function (r) { return r.university + " · " + r.degree; },
    detailPairs: function (r) {
      return [
        ["Category", CAT_LABEL[r.category] || r.category],
        ["Applications open", r.opens],
        ["Deadline", r.deadline ? fmtDate(r.deadline) : null],
        ["Deadline notes", r.deadlineNote],
        ["Tuition (approx.)", r.tuition],
        ["Fit for a lawyer moving into AI", r.fit]
      ];
    }
  });

  /* ---------- Section: Scholarships ---------- */
  makeSection({
    tab: "scholarships",
    rows: DATA.scholarships,
    defaultSort: "deadline",
    filterVal: function (r, key) { return r[key]; },
    searchText: function (r) { return [r.name, r.funds, r.value, r.eligibility].join(" "); },
    columns: [
      { key: "name", sortVal: function (r) { return r.name.toLowerCase(); } },
      { key: "funds", sortVal: function (r) { return (r.funds || "").toLowerCase(); } },
      { key: "deadline", sortVal: sortValDeadline },
      { key: "value", sortVal: function (r) { return (r.value || "").toLowerCase(); } }
    ],
    rowHtml: function (r) {
      return '<tr data-id="' + esc(r.id) + '">' +
        '<td><div class="cell-main">' + esc(r.name) + '</div><div class="cell-sub">' + esc(r.eligibility) + "</div></td>" +
        "<td>" + esc(r.funds) + "</td>" +
        '<td class="num"><div>' + esc(fmtDate(r.deadline)) + "</div><div>" + badgeHtml(r) + "</div></td>" +
        "<td>" + esc(r.value) + "</td>" +
        "</tr>";
    },
    detailTitle: function (r) { return r.name; },
    detailSub: function (r) { return r.funds; },
    detailPairs: function (r) {
      return [
        ["Value", r.value],
        ["Eligibility fit", r.eligibility],
        ["Applications open", r.opens],
        ["Deadline", r.deadline ? fmtDate(r.deadline) : null],
        ["Deadline notes", r.deadlineNote]
      ];
    }
  });

  /* ---------- Section: Startup support ---------- */
  var REGION_LABEL = { AU: "Australia", US: "USA", World: "Rest of world" };
  makeSection({
    tab: "startups",
    rows: DATA.startupSupport,
    defaultSort: "deadline",
    optionLabels: { region: REGION_LABEL },
    filterVal: function (r, key) { return r[key]; },
    searchText: function (r) { return [r.name, r.location, r.offer, r.fit].join(" "); },
    columns: [
      { key: "name", sortVal: function (r) { return r.name.toLowerCase(); } },
      { key: "region", sortVal: function (r) { return r.region + (r.location || ""); } },
      { key: "offer", sortVal: function (r) { return (r.offer || "").toLowerCase(); } },
      { key: "deadline", sortVal: sortValDeadline }
    ],
    rowHtml: function (r) {
      return '<tr data-id="' + esc(r.id) + '">' +
        '<td><div class="cell-main">' + esc(r.name) + '</div><div class="cell-sub">' + esc(r.fit) + "</div></td>" +
        '<td><span class="badge cat">' + esc(REGION_LABEL[r.region] || r.region) + "</span><div class=\"cell-sub\">" + esc(r.location || "") + "</div></td>" +
        "<td>" + esc(r.offer) + '<div class="cell-sub">' + esc(r.equity || "") + "</div></td>" +
        '<td class="num"><div>' + esc(r.deadline ? fmtDate(r.deadline) : (r.cadence || "Rolling")) + "</div><div>" + badgeHtml(r) + "</div></td>" +
        "</tr>";
    },
    detailTitle: function (r) { return r.name; },
    detailSub: function (r) { return (REGION_LABEL[r.region] || r.region) + (r.location ? " · " + r.location : ""); },
    detailPairs: function (r) {
      return [
        ["Offer", r.offer],
        ["Equity / cost", r.equity],
        ["Application cadence", r.cadence],
        ["Next deadline", r.deadline ? fmtDate(r.deadline) : null],
        ["Deadline notes", r.deadlineNote],
        ["Fit", r.fit]
      ];
    }
  });
})();
